#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Joint trajectory controller
position_trajectory_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - kr3_2_joint_a1
    - kr3_2_joint_a2
    - kr3_2_joint_a3
    - kr3_2_joint_a4
    - kr3_2_joint_a5
    - kr3_2_joint_a6
    
# Joint trajectory controller
arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - kr3_2_joint_a1
    - kr3_2_joint_a2
    - kr3_2_joint_a3
    - kr3_2_joint_a4
    - kr3_2_joint_a5
    - kr3_2_joint_a6

  #state_publish_rate: 50 # Defaults to 50
  #action_monitor_rate: 20 # Defaults to 20

# Robot_IP: "192.168.1.12"
Robot_Port: 7000 #7001
