arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
  gains:
    joint_a1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

#Robot_IP: "192.168.1.15"
Robot_Port: 7000