controller_list:
  - name: fake_KUKA1_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - kr3_1_joint_a1
      - kr3_1_joint_a2
      - kr3_1_joint_a3
      - kr3_1_joint_a4
      - kr3_1_joint_a5
      - kr3_1_joint_a6
  - name: fake_KUKA1_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - kr3_1_schunk_joint_left
      - kr3_1_schunk_joint_right
  - name: fake_KUKA2_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - kr3_2_joint_a1
      - kr3_2_joint_a2
      - kr3_2_joint_a3
      - kr3_2_joint_a4
      - kr3_2_joint_a5
      - kr3_2_joint_a6
  - name: fake_KUKA2_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - kr3_2_schunk_joint_left
      - kr3_2_schunk_joint_right
  - name: fake_KUKA3_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - kr3_3_joint_a1
      - kr3_3_joint_a2
      - kr3_3_joint_a3
      - kr3_3_joint_a4
      - kr3_3_joint_a5
      - kr3_3_joint_a6
  - name: fake_KUKA3_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_KUKA4_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - kr3_4_joint_a1
      - kr3_4_joint_a2
      - kr3_4_joint_a3
      - kr3_4_joint_a4
      - kr3_4_joint_a5
      - kr3_4_joint_a6
  - name: fake_KUKA4_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_KUKA5_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - kr4_5_joint_a1
      - kr4_5_joint_a2
      - kr4_5_joint_a3
      - kr4_5_joint_a4
      - kr4_5_joint_a5
      - kr4_5_joint_a6
  - name: fake_KUKA5_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - kr4_5_schunk_joint_left
      - kr4_5_schunk_joint_right
initial:  # Define initial robot poses per group
  - group: KUKA1_arm
    pose: home_kuka1
  - group: KUKA1_hand
    pose: open_kuka1
  - group: KUKA2_arm
    pose: home_kuka2
  - group: KUKA2_hand
    pose: open_kuka2
  - group: KUKA3_arm
    pose: home_kuka3
  - group: KUKA4_arm
    pose: home_kuka4
  - group: KUKA5_arm
    pose: home_kuka5
  - group: KUKA5_hand
    pose: open_kuka5