  KUKA1_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kr3_1_joint_a1
    - kr3_1_joint_a2
    - kr3_1_joint_a3
    - kr3_1_joint_a4
    - kr3_1_joint_a5
    - kr3_1_joint_a6
  gains:
    kr3_1_joint_a1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_1_joint_a2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_1_joint_a3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_1_joint_a4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_1_joint_a5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_1_joint_a6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
KUKA1_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kr3_1_schunk_joint_left
    - kr3_1_schunk_joint_right
  gains:
    kr3_1_schunk_joint_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_1_schunk_joint_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
KUKA2_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kr3_2_joint_a1
    - kr3_2_joint_a2
    - kr3_2_joint_a3
    - kr3_2_joint_a4
    - kr3_2_joint_a5
    - kr3_2_joint_a6
  gains:
    kr3_2_joint_a1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_2_joint_a2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_2_joint_a3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_2_joint_a4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_2_joint_a5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_2_joint_a6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
KUKA2_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kr3_2_schunk_joint_left
    - kr3_2_schunk_joint_right
  gains:
    kr3_2_schunk_joint_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_2_schunk_joint_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
KUKA3_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kr3_3_joint_a1
    - kr3_3_joint_a2
    - kr3_3_joint_a3
    - kr3_3_joint_a4
    - kr3_3_joint_a5
    - kr3_3_joint_a6
  gains:
    kr3_3_joint_a1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_3_joint_a2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_3_joint_a3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_3_joint_a4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_3_joint_a5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_3_joint_a6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
KUKA4_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kr3_4_joint_a1
    - kr3_4_joint_a2
    - kr3_4_joint_a3
    - kr3_4_joint_a4
    - kr3_4_joint_a5
    - kr3_4_joint_a6
  gains:
    kr3_4_joint_a1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_4_joint_a2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_4_joint_a3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_4_joint_a4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_4_joint_a5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr3_4_joint_a6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
KUKA5_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kr4_5_joint_a1
    - kr4_5_joint_a2
    - kr4_5_joint_a3
    - kr4_5_joint_a4
    - kr4_5_joint_a5
    - kr4_5_joint_a6
  gains:
    kr4_5_joint_a1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr4_5_joint_a2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr4_5_joint_a3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr4_5_joint_a4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr4_5_joint_a5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr4_5_joint_a6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
KUKA5_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kr4_5_schunk_joint_left
    - kr4_5_schunk_joint_right
  gains:
    kr4_5_schunk_joint_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kr4_5_schunk_joint_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1