controller_list:
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_left
      - joint_right
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
initial:  # Define initial robot poses per group
  - group: hand
    pose: open
  - group: arm
    pose: down